// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideNav: typeof import('./src/components/asideNav/index.vue')['default']
    Banners: typeof import('./src/components/banners/index.vue')['default']
    Copyright: typeof import('./src/components/copyright/index.vue')['default']
    CubeNavComp: typeof import('./src/components/cubeNavComp/index.vue')['default']
    EssayList: typeof import('./src/components/essayList/index.vue')['default']
    Flex1: typeof import('./src/components/asideNav/flex1.vue')['default']
    Flex2: typeof import('./src/components/asideNav/flex2.vue')['default']
    Flex3: typeof import('./src/components/cubeNavComp/components/flex3.vue')['default']
    Flex4: typeof import('./src/components/cubeNavComp/components/flex4.vue')['default']
    FreeContainer: typeof import('./src/components/freeContainer/index.vue')['default']
    HAddress: typeof import('./src/components/onlineForm/components/h-address.vue')['default']
    HCheckbox: typeof import('./src/components/onlineForm/components/h-checkbox.vue')['default']
    HDate: typeof import('./src/components/onlineForm/components/h-date.vue')['default']
    HEmail: typeof import('./src/components/onlineForm/components/h-email.vue')['default']
    HIDcard: typeof import('./src/components/onlineForm/components/h-IDcard.vue')['default']
    HImage: typeof import('./src/components/onlineForm/components/h-image.vue')['default']
    HInput: typeof import('./src/components/onlineForm/components/h-input.vue')['default']
    HMobile: typeof import('./src/components/onlineForm/components/h-mobile.vue')['default']
    HRadio: typeof import('./src/components/onlineForm/components/h-radio.vue')['default']
    HSelect: typeof import('./src/components/onlineForm/components/h-select.vue')['default']
    HTextarea: typeof import('./src/components/onlineForm/components/h-textarea.vue')['default']
    ImgList: typeof import('./src/components/imgList/index.vue')['default']
    ImgTextComp: typeof import('./src/components/imgTextComp/index.vue')['default']
    OnlineForm: typeof import('./src/components/onlineForm/index.vue')['default']
    OnlineMap: typeof import('./src/components/onlineMap/index.vue')['default']
    OnlineVideo: typeof import('./src/components/onlineVideo/index.vue')['default']
    Pagination: typeof import('./src/components/imgList/components/pagination.vue')['default']
    ProductsComp: typeof import('./src/components/productsComp/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollAd: typeof import('./src/components/scrollAd/index.vue')['default']
    Swiper: typeof import('./src/components/swiper/index.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanArea: typeof import('vant/es')['Area']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
